server:
  port: 8080
  servlet:
    context-path: /profile
spring:
  application:
    name: keycloak-be
  output:
    ansi:
      enabled: always # color log when running in terminal
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/keycloak-be?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/hunterkilltree

idp:
  url: http://localhost:8180
  client-id: app_germany
  client-secret: 3bpMEVmaryPn0H6SEWgCFQAU69AyFgBQ
